Verifying sv/ldv-validator-v0.8/linux-stable-5934df9-1-111_1a-drivers--scsi--gdth.ko-entry_point_ldv-val-v0.8_false-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_check_len
      ldv_copy_from_user_8
        ioc_resetdrv
          gdth_ioctl
            gdth_unlocked_ioctl
              main
              <end>
        ioc_hdrlist
          gdth_ioctl
            gdth_unlocked_ioctl
              main
              <end>
        ioc_rescan
          gdth_ioctl
            gdth_unlocked_ioctl
              main
              <end>
        ioc_lockdrv
          gdth_ioctl
            gdth_unlocked_ioctl
              main
              <end>
        ioc_event
          gdth_ioctl
            gdth_unlocked_ioctl
              main
              <end>
        ioc_general
          gdth_ioctl
            gdth_unlocked_ioctl
              main
              <end>
        ioc_general
          gdth_ioctl
            gdth_unlocked_ioctl
              main
              <end>
        gdth_ioctl
          gdth_unlocked_ioctl
            main
            <end>
        gdth_ioctl
          gdth_unlocked_ioctl
            main
            <end>
        gdth_ioctl
          gdth_unlocked_ioctl
            main
            <end>
      ldv___copy_user_nocache_6
      <end>
      ldv___copy_user_nocache_5
      <end>
      ldv__copy_to_user_4
        copy_to_user
          ioc_resetdrv
          ioc_hdrlist
          ioc_rescan
          ioc_event
          ioc_general
          ioc_general
      ldv__copy_from_user_3
        copy_from_user
          ldv_copy_from_user_8
            ioc_resetdrv
            ioc_hdrlist
            ioc_rescan
            ioc_lockdrv
            ioc_event
            ioc_general
            ioc_general
