Verifying sv/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--usb--serial--usbserial.ko-entry_point_false-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_module_put
      ldv_module_put_and_exit
      <end>
      ldv_module_put_19
        usb_serial_probe
          main
          <end>
          usb_serial_register_drivers
            usb_serial_generic_register
              usb_serial_init
                main
                <end>
      ldv_module_put_18
        usb_serial_probe
          main
          <end>
          usb_serial_register_drivers
            usb_serial_generic_register
              usb_serial_init
                main
                <end>
      ldv_module_put_17
        usb_serial_probe
          main
          <end>
          usb_serial_register_drivers
            usb_serial_generic_register
              usb_serial_init
                main
                <end>
      ldv_module_put_16
        usb_serial_probe
          main
          <end>
          usb_serial_register_drivers
            usb_serial_generic_register
              usb_serial_init
                main
                <end>
      ldv_module_put_15
        usb_serial_probe
          main
          <end>
          usb_serial_register_drivers
            usb_serial_generic_register
              usb_serial_init
                main
                <end>
      ldv_module_put_14
        usb_serial_probe
          usb_serial_register_drivers
            usb_serial_generic_register
              usb_serial_init
      ldv_module_put_12
        serial_cleanup
      ldv_module_put_11
        serial_install
    ldv_check_final_state
