Verifying sv/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--usb--serial--digi_acceleport.ko-entry_point_true-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_check_alloc_nonatomic
    <end>
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_flags
      kzalloc
        digi_port_init
          digi_startup
            main
            <end>
            main
            <end>
          digi_port_probe
            main
            <end>
            main
            <end>
            main
            <end>
            main
            <end>
            main
            <end>
            main
            <end>
            main
            <end>
            main
            <end>
        digi_startup
      ldv_usb_submit_urb_35
        digi_read_bulk_callback
      ldv_usb_submit_urb_34
        digi_startup_device
          digi_open
      ldv_usb_submit_urb_33
        digi_write_bulk_callback
      ldv_usb_submit_urb_32
        digi_write
      ldv_usb_submit_urb_31
        digi_rx_unthrottle
      ldv_usb_submit_urb_30
        digi_set_modem_signals
          digi_tiocmset
          digi_set_termios
            digi_open
          digi_set_termios
            digi_open
          digi_dtr_rts
      ldv_usb_submit_urb_29
        digi_write_inb_command
          digi_transmit_idle
            digi_close
          digi_break_ctl
      ldv_usb_submit_urb_28
        digi_write_oob_command
          digi_close
          digi_set_termios
            digi_open
          digi_open
      ldv_kmem_cache_alloc_25
      <end>
