Verifying sv/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--vfio--vfio.ko-entry_point_false-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_module_put
      ldv_module_put_and_exit
      <end>
      ldv_module_put_11
        __vfio_group_unset_container
          vfio_group_unset_container
            vfio_group_fops_unl_ioctl
              vfio_group_fops_compat_ioctl
                main
                <end>
              main
              <end>
          vfio_group_try_dissolve_container
            vfio_group_fops_release
              main
              <end>
            vfio_device_fops_release
              main
              <end>
            vfio_group_put_external_user
      ldv_module_put_10
        vfio_ioctl_set_iommu
          vfio_fops_unl_ioctl
            vfio_fops_compat_ioctl
              main
              <end>
            main
            <end>
      ldv_module_put_9
        vfio_ioctl_set_iommu
          vfio_fops_unl_ioctl
            vfio_fops_compat_ioctl
              main
              <end>
            main
            <end>
      ldv_module_put_8
        vfio_ioctl_set_iommu
          vfio_fops_unl_ioctl
            vfio_fops_compat_ioctl
              main
              <end>
            main
            <end>
      ldv_module_put_6
        vfio_ioctl_check_extension
          vfio_fops_unl_ioctl
            vfio_fops_compat_ioctl
          vfio_external_check_extension
    ldv_check_final_state
