Verifying sv/ldv-linux-3.16-rc1/43_2a_bitvector_linux-3.16-rc1.tar.xz-43_2a-drivers--usb--dwc3--dwc3.ko-entry_point_false-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_check_alloc_nonatomic
    <end>
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_flags
      ldv_kmem_cache_alloc_114
      <end>
      ldv_kmem_cache_alloc_92
      <end>
      ldv_kmem_cache_alloc_64
      <end>
      kzalloc
        dwc3_gadget_init_hw_endpoints
          dwc3_gadget_init_endpoints
            dwc3_gadget_init
              dwc3_core_init_mode
                dwc3_probe
                  main
                  <end>
              dwc3_core_init_mode
                dwc3_probe
                  main
                  <end>
          dwc3_gadget_init_endpoints
            dwc3_gadget_init
              dwc3_core_init_mode
                dwc3_probe
                  main
                  <end>
              dwc3_core_init_mode
                dwc3_probe
                  main
                  <end>
        dwc3_debugfs_init
          dwc3_probe
            main
            <end>
        dwc3_gadget_ep_alloc_request
          ldv_main_exported_8
            main
            <end>
          ldv_main_exported_7
            main
            <end>
        dwc3_gadget_init
          dwc3_core_init_mode
            dwc3_probe
              main
              <end>
          dwc3_core_init_mode
            dwc3_probe
              main
              <end>
      ldv_kmem_cache_alloc_42
      <end>
      ldv_kmem_cache_alloc_16
      <end>
    ldv__builtin_trap
    <end>
