Verifying sv/ldv-linux-3.16-rc1/43_2a_bitvector_linux-3.16-rc1.tar.xz-43_2a-drivers--usb--gadget--pch_udc.ko-entry_point_false-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_check_alloc_nonatomic
    <end>
    ldv_check_alloc_flags_and_return_some_page
    <end>
    ldv_check_alloc_flags
      kzalloc
        init_dma_pools
          pch_udc_probe
            main
            <end>
        pch_udc_probe
          main
          <end>
        pch_udc_alloc_request
          main
          <end>
        pch_udc_pcd_queue
          main
          <end>
      ldv_dma_pool_alloc_25
        init_dma_pools
          pch_udc_probe
            main
            <end>
      ldv_dma_pool_alloc_24
        init_dma_pools
          pch_udc_probe
            main
            <end>
      ldv_dma_pool_alloc_23
        pch_udc_alloc_request
          main
          <end>
      ldv_dma_pool_alloc_22
        pch_udc_create_dma_chain
          prepare_dma
            pch_udc_pcd_queue
              main
              <end>
      ldv_kmem_cache_alloc_16
      <end>
    ldv__builtin_trap
    <end>
