Verifying sv/ldv-validator-v0.6/linux-stable-39a1d13-1-101_1a-drivers--block--virtio_blk.ko-entry_point_false-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_put_blk_rq
    <end>
    ldv_blk_get_request
    <end>
    ldv_blk_make_request
      ldv_blk_make_request_5
        virtblk_get_id
          virtblk_ioctl
            main
            <end>
    ldv_check_final_state
      main
      <end>
    ldv__builtin_trap
    <end>
