Verifying sv/ldv-validator-v0.6/linux-stable-5742d35-1-136_1a-drivers--usb--serial--ti_usb_3410_5052.ko-entry_point_false-unreach-call.cil.out.c
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_error
    ldv_der
      ldv_usb_deregister_8
        ti_exit
          main
          <end>
    ldv_s_der
      ldv_usb_serial_deregister_7
        ti_exit
          main
          <end>
      ldv_usb_serial_deregister_6
        ti_exit
          main
          <end>
      ldv_usb_serial_deregister_5
        ti_init
          main
          <end>
      ldv_usb_serial_deregister_4
        ti_init
          main
          <end>
    ldv_s_der
      ldv_usb_serial_deregister_7
        ti_exit
          main
          <end>
      ldv_usb_serial_deregister_6
        ti_exit
          main
          <end>
      ldv_usb_serial_deregister_5
        ti_init
          main
          <end>
      ldv_usb_serial_deregister_4
        ti_init
          main
          <end>
    ldv_check_final_state
      main
      <end>
    ldv_check_final_state
    ldv__builtin_trap
    <end>
