Verifying sv/ldv-linux-3.0/usb_urb-drivers-net-can-usb-ems_usb.ko_false-unreach-call.cil.out.i.pp.i
main using GenerateFunctionCallPreprocessor ...
GenerateFunctionCallPreprocessor parents for __VERIFIER_error:
__VERIFIER_error
  ldv_blast_assert
    usb_free_urb
      ems_usb_start
        ems_usb_open
          main
          <end>
      ems_usb_start
        ems_usb_open
          main
          <end>
      ems_usb_disconnect
        main
        <end>
      ems_usb_probe
        main
        <end>
      ems_usb_start_xmit
        main
        <end>
      ems_usb_start_xmit
        main
        <end>
    usb_free_coherent
      ems_usb_write_bulk_callback
        ems_usb_start_xmit
          main
          <end>
      ems_usb_start
        ems_usb_open
          main
          <end>
      ems_usb_start_xmit
        main
        <end>
      ems_usb_start_xmit
        main
        <end>
    ldv_check_final_state
    ldv_check_final_state
